export type JobLevel = 'C_SUITE' | 'VP' | 'DIRECTOR' | 'MANAGER' | 'OTHER_EXECUTIVE'

export type NotificationType =
  | 'APPLICATION_RECEIVED'
  | 'APPLICATION_STATUS_CHANGED'
  | 'JOB_APPROVED'
  | 'JOB_REJECTED'
  | 'EMPLOYER_APPROVED'
  | 'EMPLOYER_REJECTED'
  | 'NEW_MESSAGE'
  | 'INTERVIEW_SCHEDULED'
  | 'INTERVIEW_UPDATED'
  | 'JOB_MATCH'